export const USERS =[{
    user:'Ashir',
    image:require('../assets/images/oo.jpg'),
    post:require('../assets/images/pi.jpg')
},
{
    user:'Zuhaib',
    image:require('../assets/images/pi.jpg'),
    post:require('../assets/images/py.jpg'),
},
{
    user:'Basit',
    image:require('../assets/images/pp.jpg'),
    post:require('../assets/images/pu.jpg')
},
{
    user:'jamal',
    image:require('../assets/images/pi.jpg'),
    post:require('../assets/images/py.jpg'),
},
{
    user:'Amir',
    image:require('../assets/images/py.jpg'),
    post:require('../assets/images/pp.jpg')
},
{
    user:'Jabba',
    image:require('../assets/images/pu.jpg'),
    post:require('../assets/images/py.jpg'),
},
{
    user:'Asdf',
    image:require('../assets/images/pi.jpg'),
    post:require('../assets/images/pp.jpg')
},
]